language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-22.0.1
    - extra-android-m2repository
    - extra-android-support

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle