language: android
jdk: oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-22.0.1
    - add-on
    - extra

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle