language: android
jdk: oraclejdk7

android:
  components:
    - android-23
    - build-tools-23.0.2
    - add-on
    - extra

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle