language: android
jdk: oraclejdk8
# Use the Travis Sudo-enabled VM Infrastructure
sudo: required
dist: precise

#cache:
#  directories:
#    - ${TRAVIS_BUILD_DIR}/gradle/caches/
#    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ANDROID_API_LEVEL=21
    - ANDROID_APP_BUILD_TOOLS_VERSION=25.0.3
    - ANDROID_ELK_BUILD_TOOLS_VERSION=25.0.0
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

notifications:
  email:
    - elizarov1988@gmail.com
    - matek3022@gmail.com
#    - sklyarovdv@mos.ru
#    - fastsilver2009@gmail.com

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # to install Android SDK tools 25.1.x
    - build-tools-$ANDROID_APP_BUILD_TOOLS_VERSION
    - build-tools-$ANDROID_ELK_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - yes | sdkmanager "platforms;android-25"
  - yes | sdkmanager "platforms;android-${ANDROID_API_LEVEL}"

before_script:
  - ./gradlew assembleCodecov jacocoTestReport assembleAndroidTest
  # Create and start emulator
  - echo no | android create avd --force -n test1 -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test1 -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb -s emulator-5554 shell input keyevent 82 &

script:
  - ./gradlew createCodecovCoverageReport
  - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)