/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the AnnotatedSQL library.
  */
 
package ru.mos.elk.db;

import android.database.sqlite.SQLiteDatabase;

public class UserSchema{

	public static final String DB_NAME = "elk_user_data.db";
	public static final int DB_VERSION = 6; //в версии 1.8.1 db_version стала 3, для версии 1.9 - 4, для версии 1.9.1 - 5 и до версии 1.9.6, с версии 2.0.0 - 6

    //tables
    public static final String SQL_CREATE_CARS = "create table cars( car_number TEXT, _id INTEGER PRIMARY KEY, is_default INTEGER, sts_number TEXT, vehicle_id INTEGER)";

    public static final String SQL_CREATE_BLACKLIST = "create table blacklist( author TEXT, _id INTEGER PRIMARY KEY, type INTEGER, block_id INTEGER)";

    public static final String SQL_CREATE_TIMES = "create table times( _id INTEGER PRIMARY KEY, is_checked INTEGER, name TEXT, id INTEGER)";

    public static final String SQL_CREATE_SUBSCRIPTIONS = "create table subscriptions( email INTEGER, _id INTEGER PRIMARY KEY, push INTEGER, sms INTEGER, type TEXT)";

    public static final String SQL_CREATE_ROADS = "create table roads( group_id INTEGER, _id INTEGER PRIMARY KEY, is_checked TEXT, name TEXT, road_id TEXT)";

    public static final String SQL_CREATE_ROADGROUPS = "create table roadgroups( _id INTEGER PRIMARY KEY, group_name TEXT)";

    public static final String SQL_CREATE_FLATS = "create table flats( building TEXT, electro_account TEXT, electro_device TEXT, epd TEXT, flat TEXT, flat_id INTEGER, building_id TEXT, _id INTEGER PRIMARY KEY, is_default INTEGER, hotwater_available INTEGER, street TEXT, is_residence INTEGER, is_registration INTEGER, is_work INTEGER, editing_blocked INTEGER, city TEXT, district TEXT, area TEXT, area_id TEXT)";

    //indexes
    //views
    //queries
    public static final String SQL_QUERY_ROADS_PATH = "SELECT r.road_id as _id, r.road_id, r.name, r.is_checked, rg.group_name FROM roads as r JOIN roadgroups AS rg ON rg._id = r.group_id";


    public static void onCreate(final SQLiteDatabase db) {
        db.execSQL(SQL_CREATE_CARS);
        db.execSQL(SQL_CREATE_BLACKLIST);
        db.execSQL(SQL_CREATE_TIMES);
        db.execSQL(SQL_CREATE_SUBSCRIPTIONS);
        db.execSQL(SQL_CREATE_ROADS);
        db.execSQL(SQL_CREATE_ROADGROUPS);
        db.execSQL(SQL_CREATE_FLATS);
    }

    public static void onDrop(final SQLiteDatabase db){
        db.execSQL("drop table if exists cars");
        db.execSQL("drop table if exists blacklist");
        db.execSQL("drop table if exists times");
        db.execSQL("drop table if exists subscriptions");
        db.execSQL("drop table if exists roads");
        db.execSQL("drop table if exists roadgroups");
        db.execSQL("drop table if exists flats");

    }
}