/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the AnnotatedSQL library.
  */

package ru.mos.polls.db;

import android.database.sqlite.SQLiteDatabase;

public class PollsSchema {

    public static final String DB_NAME = "polls_data.db";
    public static final int DB_VERSION = 7; // в версии 1.8.1 версия кода 7

    //tables
    public static final String SQL_CREATE_QUESTIONS = "create table questions( _id INTEGER PRIMARY KEY, poll_id INTEGER, question TEXT, question_id INTEGER, type INTEGER)";

    public static final String SQL_CREATE_POLL_GROUPS = "create table poll_groups( _id INTEGER PRIMARY KEY, title TEXT, group_id INTEGER)";

    public static final String SQL_CREATE_POLLS = "create table polls( group_id INTEGER, _id INTEGER PRIMARY KEY, status INTEGER, points INTEGER, poll_id INTEGER, title TEXT, author TEXT, quest_count INTEGER, mark TEXT)";

    public static final String SQL_CREATE_VARIANTS = "create table variants( _id INTEGER PRIMARY KEY, input_type INTEGER, kind INTEGER, max TEXT, min TEXT, rightText TEXT, text TEXT, variant_id INTEGER)";

    public static final String SQL_CREATE_POINT_HISTORY = "create table point_history(_id INTEGER PRIMARY KEY, title TEXT, write_off_date INTEGER, points INTEGER, refill INTEGER, action TEXT)";

    public static final String SQL_DROP_POLLS = "drop table if exists polls";
    public static final String SQL_DROP_POLLS_GROUPS = "drop table if exists poll_groups";
    public static final String SQL_DROP_QUESTIONS = "drop table if exists questions";
    public static final String SQL_DROP_VARIANTS = "drop table if exists variants";


    //indexes
    //views
    public static final String SQL_CREATE_POLLGROUP_VIEW = "CREATE VIEW view_group AS SELECT  polls.poll_id as _id, polls.title as polls_title, polls.points as polls_points, polls.status as polls_status, polls.author as polls_author, polls.mark as polls_mark, polls.quest_count as polls_quest_count, gr.group_id as gr_group_id, gr.title as gr_title FROM polls AS polls JOIN poll_groups AS gr ON gr.group_id = polls.group_id";

    public static final String SQL_ADD_ACTION_TO_POINT_HISTORY = "ALTER TABLE point_history ADD action TEXT;";

    public static final String SQL_CLEAR_POINT_HISTORY = "DELETE FROM point_history;";
    //queries

    public static void onCreate(final SQLiteDatabase db) {
        /**
         * эти таблицы используется при кешировании списка голосований
         */
//        db.execSQL(SQL_CREATE_QUESTIONS);
//        db.execSQL(SQL_CREATE_POLL_GROUPS);
//        db.execSQL(SQL_CREATE_POLLS);
//        db.execSQL(SQL_CREATE_VARIANTS);
//        db.execSQL(SQL_CREATE_POLLGROUP_VIEW);
        db.execSQL(SQL_CREATE_POINT_HISTORY);


    }

    public static void onDrop(final SQLiteDatabase db) {
        db.execSQL("drop table if exists questions");
        db.execSQL("drop table if exists poll_groups");
        db.execSQL("drop table if exists polls");
        db.execSQL("drop table if exists variants");
        db.execSQL("drop table if exists point_history");

        db.execSQL("drop view if exists view_group");
    }
}